### ISSUE TITLE
RSS: Earth not shown

### ISSUE THREAD

**Issue by Gordon-Dry** [severedsolo/WhereCanIGo#5]
I recognized you added the parameter
`displayName = Earth`
because the celestial body name still is "Kerbin".
But it seems that is not enough.

The entry for Earth is completely missing in VAB now.
I have to admit that the vessel is not capable of orbiting (RP-1 is hard), but that should not be the reason I would say.

**Comment by severedsolo** [comment]
Can I get the log from just after you try and open the window in the Editor please. Fairly certain I know what it is, but just want confirmation

**Comment by severedsolo** [comment]
Figured it out. Earth is actually called Earth. I guess the Kopernicus files change it somewhere before the Editor loads.

**Comment by Gordon-Dry** [comment]
I'm not sure if the logic inside RSS was reverted, actually I have issues and to troubleshoot I try it with
```
			name = Kerbin
			displayName = Earth
```
as it was before and see what happens.

**Comment by Gordon-Dry** [comment]
No, that's not the issue.
